name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Rebuild LightningCSS for Linux
        run: npm rebuild lightningcss
      - name: Create .env.test
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.test
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.test
          echo "API_URL=${{ secrets.API_URL }}" >> .env.test
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.test
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.test
      - name: Build project
        run: npm run build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Run frontend tests and collect coverage
        run: npx jest --config jest.frontend.config.js --coverage --coverageDirectory=coverage-frontend
      - name: Run backend tests and collect coverage
        run: npx jest --config jest.backend.config.js --coverage --coverageDirectory=coverage-backend
      - name: Merge coverage reports
        run: |
          npx mkdirp coverage
          npx lcov-result-merger 'coverage-frontend/lcov.info' 'coverage-backend/lcov.info' > coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=wzzzzwwzw_TFM
            -Dsonar.organization=wzzzzwwzw
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/lib/nextauth.*
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}